---

- name: Create our install-config.yaml file
  template:
    src: "./templates/install-config.yml.j2"
    dest: "{{  base_directory }}/temp/install-config.yaml"
    owner: root
    group: root
    mode: 0644

- name: Create our install ignition config
  command:
    cmd: >
      openshift-install
      --dir={{  base_directory }}/temp
      create
      single-node-ignition-config
  args:
    creates: "{{  base_directory }}/temp/bootstrap-in-place-for-live-iso.ign"

# yamllint disable rule:line-length
- name: Create our network interface nmconnection file
  template:
    src: "./templates/interface.nmconnection.j2"
    dest: "{{  base_directory }}/temp/{{ openshift.network.interface }}.nmconnection"
    owner: root
    group: root
    mode: 0644
# yamllint enable rule:line-length
-
- name: Create our ignition config file
  template:
    src: "./templates/networking-ignition.yml.j2"
    dest: "{{  base_directory }}/temp/networking-ignition.yaml"
    owner: root
    group: root
    mode: 0644

- name: Copy our single-node-ignition-config.ig file to our iso directory
  command:
    cmd: >
      cp {{  base_directory }}/temp/bootstrap-in-place-for-live-iso.ign
      {{  base_directory }}/iso/iso.ign
  args:
    creates: "{{  base_directory }}/iso/iso.ign"

- name: Create our CoreOS boot iso
  shell: >
      podman run --privileged --rm -v
      /dev:/dev -v /run/udev:/run/udev
      -v {{  base_directory }}/iso:/data
      -w /data quay.io/coreos/coreos-installer:release
      iso
      ignition
      embed
      -fi iso.ign
      rhcos-live.x86_64.iso
  # noqa no-changed-when

# yamllint disable rule:line-length
- name: Add our network customisations
  shell: >
      coreos-installer
      iso customize
      --network-keyfile {{  base_directory }}/temp/{{ openshift.network.interface }}.nmconnection
      {{  base_directory }}/iso/rhcos-live.x86_64.iso
  # noqa no-changed-when
# yamllint enable rule:line-length
