---

- name: Install Container Tools Group
  dnf:
    name:
      - "@container-tools"
      - jq
    state: present

- name: Download the latest coreos installer tool
  get_url:
    url: "{{ mirror_url }}/coreos-installer/latest/coreos-installer"
    dest: /bin/coreos-installer
    mode: 0700

- name: Download our openshift binaries
  unarchive:
    src: "{{ dl_url + binary }}"
    dest: "/usr/bin"
    remote_src: true
    mode: 0700
  loop: "{{ config.binaries }}"
  loop_control:
    loop_var: binary

- name: Get our butane binary
  get_url:
    url: "{{ butane.base_url + butane.version + '/' + butane.binary }}"
    dest: "/usr/bin/butane"
    mode: 0700

- name: Get our CoreOS iso url
  shell: >
    set -o pipefail;
    openshift-install coreos print-stream-json |
    grep location |
    grep x86_64 |
    grep iso |
    cut -d\" -f4
  changed_when: true
  register: coreos_iso_url

- name: Download our CoreOS iso
  get_url:
    url: "{{ coreos_iso_url.stdout }}"
    dest: "{{  base_directory }}/iso/rhcos-live.x86_64.iso"
