---

- block:
    - name: Ensure our public key exists
      stat:
        path: "{{ install_config.pub_key_path }}"
      register: pub_key_path_test

    - block:
        - name: Unset our path so we can rebuild our key
          set_fact:
            install_config: "{{ install_config | combine({ 'pub_key_path': '' }, recursive=true) }}"
      when: not pub_key_path_test.stat.exists

    - block:
        - name: Read our key contents
          command:
            cmd: "cat {{ install_config.pub_key_path }}"
          register: pub_key_data
          changed_when: pub_key_data.rc != 0
          failed_when: pub_key_data.rc != 0

        - name: Export our public key to the variable
          set_fact:
            install_config: "{{ install_config | combine({ 'pub_key_contents': pub_key_data.stdout }, recursive=true) }}"
      when: pub_key_path.stat.exists
  when: install_config.pub_key_path != ""

- block:
    - name: Ensure that root has a .ssh directory
      file:
        state: directory
        path: "/root/.ssh/"
        mode: 0600
        owner: root
        group: root

    - name: Ensure we have a ssh key for OpenShift
      openssh_keypair:
        path: /root/.ssh/id_ed25519
        regenerate: full_idempotence
        type: ed25519
      register: root_ssh_key

    - name: Export our public key to the variable
      set_fact:
        install_config: "{{ install_config | combine({ 'pub_key_contents': root_ssh_key.public_key }, recursive=true) }}"
  when: install_config.pub_key_path == ""

- name: Debug
  debug:
    msg: "{{ install_config, install_config.openshift_pull_secret_path == '' }}"
- block:
    - name: Get stat on our pull secret file
      stat:
        path: "{{ install_config.openshift_pull_secret_path }}"
      register: pull_secret_file

    - block:
        - name: Read our contents of our pull secret file
          command:
            cmd: "cat {{ install_config.openshift_pull_secret_path }}"
          register: pull_secret_contents
          changed_when: pull_secret_contents.rc != 0
          failed_when: pull_secret_contents.rc != 0

        - name: Set pull secret fact
          set_fact:
            install_config: "{{ install_config | combine({ 'openshift_pull_secret': pull_secret_contents.stdout }, recursive=true) }}"
      when: pull_secret_file.stat.exists
  when: install_config.openshift_pull_secret_path != ""

- name: Ensure that our installation directory and paths exist
  file:
    state: directory
    path: "{{ config.base_dir }}/{{ directory }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ config.sub_dir }}"
  loop_control:
    loop_var: directory

- name: Install Container Tools Group
  dnf:
    name: "@container-tools"
    state: present
